=begin
#Virtual Private Cloud API

#The IBM Cloud Virtual Private Cloud (VPC) API can be used to programmatically provision and manage infrastructure resources, including virtual server instances, subnets, volumes, and load balancers.

The version of the OpenAPI document: 2020-11-17

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-beta2

=end

require 'spec_helper'
require 'json'

# Unit tests for IbmCloudVpc::LoadBalancersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoadBalancersApi' do
  before do
    # run before each test
    @api_instance = IbmCloudVpc::LoadBalancersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoadBalancersApi' do
    it 'should create an instance of LoadBalancersApi' do
      expect(@api_instance).to be_instance_of(IbmCloudVpc::LoadBalancersApi)
    end
  end

  # unit tests for create_load_balancer
  # Create and provision a load balancer
  # This request creates and provisions a new load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_prototype The load balancer prototype object
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancer]
  describe 'create_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_load_balancer_listener
  # Create a listener
  # This request creates a new listener to the load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param load_balancer_listener_prototype The load balancer listener prototype object
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListener]
  describe 'create_load_balancer_listener test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_load_balancer_listener_policy
  # Create a policy for the load balancer listener
  # Creates a new policy to the load balancer listener.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param load_balancer_listener_policy_prototype The listener policy prototype object
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicy]
  describe 'create_load_balancer_listener_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_load_balancer_listener_policy_rule
  # Create a rule for the load balancer listener policy
  # Creates a new rule for the load balancer listener policy.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param policy_id The policy identifier
  # @param load_balancer_listener_policy_rule_prototype The listener policy rule prototype object
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicyRule]
  describe 'create_load_balancer_listener_policy_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_load_balancer_pool
  # Create a load balancer pool
  # This request creates a new pool from a pool prototype object.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param load_balancer_pool_prototype The load balancer pool prototype object.
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPool]
  describe 'create_load_balancer_pool test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_load_balancer_pool_member
  # Create a member in the load balancer pool
  # This request creates a new member and adds the member to the pool.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param pool_id The pool identifier
  # @param load_balancer_pool_member_prototype The prototype object for a new load balancer pool member. For load balancers in the &#x60;network&#x60; family, the same &#x60;port&#x60; and &#x60;target&#x60; tuple cannot be shared by a pool member of any other load balancer.
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPoolMember]
  describe 'create_load_balancer_pool_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_load_balancer
  # Delete a load balancer
  # This request deletes a load balancer. This operation cannot be reversed.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param id The load balancer identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_load_balancer_listener
  # Delete a listener
  # This request deletes a load balancer listener. This operation cannot be reversed.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param id The listener identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer_listener test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_load_balancer_listener_policy
  # Delete a policy of the load balancer listener
  # Deletes a policy of the load balancer listener. This operation cannot be reversed.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param id The policy identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer_listener_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_load_balancer_listener_policy_rule
  # Delete a rule from the load balancer listener policy
  # Deletes a rule from the load balancer listener policy. This operation cannot be reversed.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param policy_id The policy identifier
  # @param id The rule identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer_listener_policy_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_load_balancer_pool
  # Delete a pool
  # This request deletes a load balancer pool. This operation cannot be reversed. The pool must not currently be the default pool for any listener in the load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param id The pool identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer_pool test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_load_balancer_pool_member
  # Delete a member from the load balancer pool
  # This request deletes a member from the pool. This operation cannot be reversed.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param pool_id The pool identifier
  # @param id The member identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_load_balancer_pool_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer
  # Retrieve a load balancer
  # This request retrieves a single load balancer specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param id The load balancer identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancer]
  describe 'get_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_listener
  # Retrieve a listener
  # This request retrieves a single listener specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param id The listener identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListener]
  describe 'get_load_balancer_listener test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_listener_policy
  # Retrieve a policy of the load balancer listener
  # Retrieve a single policy specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param id The policy identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicy]
  describe 'get_load_balancer_listener_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_listener_policy_rule
  # Retrieve a rule of the load balancer listener policy
  # Retrieves a single rule specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param policy_id The policy identifier
  # @param id The rule identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicyRule]
  describe 'get_load_balancer_listener_policy_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_pool
  # Retrieve a load balancer pool
  # This request retrieves a single pool specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param id The pool identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPool]
  describe 'get_load_balancer_pool test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_pool_member
  # Retrieve a member in the load balancer pool
  # This request retrieves a single member specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param pool_id The pool identifier
  # @param id The member identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPoolMember]
  describe 'get_load_balancer_pool_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_profile
  # Retrieve specified load balancer profile
  # This request retrieves a load balancer profile specified by the name in the URL.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param name The load balancer profile name
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerProfile]
  describe 'get_load_balancer_profile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_load_balancer_statistics
  # List statistics of a load balancer
  # This request lists statistics of a load balancer specified by the identifier in the URL path.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param id The load balancer identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerStatistics]
  describe 'get_load_balancer_statistics test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancer_listener_policies
  # List all policies of the load balancer listener
  # Retrieves a list of all policies belonging to the load balancer listener.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicyCollection]
  describe 'list_load_balancer_listener_policies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancer_listener_policy_rules
  # List all rules of the load balancer listener policy
  # Retrieves a list of all rules belonging to the load balancer listener policy.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param policy_id The policy identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicyRuleCollection]
  describe 'list_load_balancer_listener_policy_rules test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancer_listeners
  # List all listeners of the load balancer
  # This request retrieves a list of all listeners that belong to the load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerCollection]
  describe 'list_load_balancer_listeners test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancer_pool_members
  # List all members of the load balancer pool
  # This request retrieves a paginated list of all members that belong to the pool.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param pool_id The pool identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPoolMemberCollection]
  describe 'list_load_balancer_pool_members test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancer_pools
  # List all pools of the load balancer
  # This request lists all pools that belong to the load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPoolCollection]
  describe 'list_load_balancer_pools test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancer_profiles
  # List all load balancer profiles
  # This request lists all load balancer profiles available in the region. A load balancer profile specifies the performance characteristics and pricing model for a load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start A server-supplied token determining what resource to start the page on
  # @option opts [Integer] :limit The number of resources to return on a page
  # @return [LoadBalancerProfileCollection]
  describe 'list_load_balancer_profiles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_load_balancers
  # List all load balancers
  # This request retrieves a paginated list of all load balancers that belong to this account.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerCollection]
  describe 'list_load_balancers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace_load_balancer_pool_members
  # Update members of the load balancer pool
  # This request updates members of the load balancer pool from a collection of member prototype objects.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param pool_id The pool identifier
  # @param load_balancer_pool_member_collection_prototype The collection of prototype objects for load balancer pool members. For load balancers in the &#x60;network&#x60; family, the same &#x60;port&#x60; and &#x60;target&#x60; tuple cannot be shared by a pool member of any other load balancer.
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPoolMemberCollection]
  describe 'replace_load_balancer_pool_members test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_load_balancer
  # Update a load balancer
  # This request updates a load balancer.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param id The load balancer identifier
  # @param load_balancer_patch The load balancer patch
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancer]
  describe 'update_load_balancer test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_load_balancer_listener
  # Update a listener
  # This request updates a load balancer listener from a listener patch.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param id The listener identifier
  # @param load_balancer_listener_patch The load balancer listener patch
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListener]
  describe 'update_load_balancer_listener test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_load_balancer_listener_policy
  # Update a policy of the load balancer listener
  # Updates a policy from a policy patch.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param id The policy identifier
  # @param load_balancer_listener_policy_patch The listener policy patch
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicy]
  describe 'update_load_balancer_listener_policy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_load_balancer_listener_policy_rule
  # Update a rule of the load balancer listener policy
  # Updates a rule of the load balancer listener policy.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param listener_id The listener identifier
  # @param policy_id The policy identifier
  # @param id The rule identifier
  # @param load_balancer_listener_policy_rule_patch The listener policy rule patch.
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerListenerPolicyRule]
  describe 'update_load_balancer_listener_policy_rule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_load_balancer_pool
  # Update a load balancer pool
  # This request updates a load balancer pool from a pool patch.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param id The pool identifier
  # @param load_balancer_pool_patch The load balancer pool patch
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPool]
  describe 'update_load_balancer_pool test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_load_balancer_pool_member
  # Update a member in the load balancer pool
  # This request updates an existing member from a member patch.
  # @param version Requests the version of the API as of a date in the format &#x60;YYYY-MM-DD&#x60;. Any date up to the current date may be provided. Specify the current date to request the latest version.
  # @param generation The infrastructure generation for the request. For the API behavior documented here, use &#x60;2&#x60;.
  # @param load_balancer_id The load balancer identifier
  # @param pool_id The pool identifier
  # @param id The member identifier
  # @param load_balancer_pool_member_patch The load balancer pool member patch
  # @param [Hash] opts the optional parameters
  # @return [LoadBalancerPoolMember]
  describe 'update_load_balancer_pool_member test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
