=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 2.3.1
Contact: ismirlia@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::AccessConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::AccessConfig do
  let(:instance) { IbmCloudPower::AccessConfig.new }

  describe 'test an instance of AccessConfig' do
    it 'should create an instance of AccessConfig' do
      expect(instance).to be_instance_of(IbmCloudPower::AccessConfig)
    end
  end
end
