=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 2.3.1
Contact: ismirlia@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::AvailableHostCapacity
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::AvailableHostCapacity do
  let(:instance) { IbmCloudPower::AvailableHostCapacity.new }

  describe 'test an instance of AvailableHostCapacity' do
    it 'should create an instance of AvailableHostCapacity' do
      expect(instance).to be_instance_of(IbmCloudPower::AvailableHostCapacity)
    end
  end
  describe 'test attribute "cores"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "memory"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
