=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 2.3.1
Contact: ismirlia@us.ibm.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::CloudConnectionCreateClassic
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::CloudConnectionCreateClassic do
  let(:instance) { IbmCloudPower::CloudConnectionCreateClassic.new }

  describe 'test an instance of CloudConnectionCreateClassic' do
    it 'should create an instance of CloudConnectionCreateClassic' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(IbmCloudPower::CloudConnectionCreateClassic)
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "gre"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
