=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 1.0.0
Contact: kylej@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::DisasterRecoveryLocation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::DisasterRecoveryLocation do
  let(:instance) { IbmCloudPower::DisasterRecoveryLocation.new }

  describe 'test an instance of DisasterRecoveryLocation' do
    it 'should create an instance of DisasterRecoveryLocation' do
      expect(instance).to be_instance_of(IbmCloudPower::DisasterRecoveryLocation)
    end
  end
  describe 'test attribute "location"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "replication_sites"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
