=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 2.3.1
Contact: ismirlia@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::NetworkSecurityGroupsAction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::NetworkSecurityGroupsAction do
  let(:instance) { IbmCloudPower::NetworkSecurityGroupsAction.new }

  describe 'test an instance of NetworkSecurityGroupsAction' do
    it 'should create an instance of NetworkSecurityGroupsAction' do
      expect(instance).to be_instance_of(IbmCloudPower::NetworkSecurityGroupsAction)
    end
  end
  describe 'test attribute "action"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["enable", "disable"])
      # validator.allowable_values.each do |value|
      #   expect { instance.action = value }.not_to raise_error
      # end
    end
  end

end
