=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 2.3.1
Contact: ismirlia@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::VolumesAttach
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::VolumesAttach do
  let(:instance) { IbmCloudPower::VolumesAttach.new }

  describe 'test an instance of VolumesAttach' do
    it 'should create an instance of VolumesAttach' do
      expect(instance).to be_instance_of(IbmCloudPower::VolumesAttach)
    end
  end
  describe 'test attribute "volume_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
