=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 1.0.0
Contact: kylej@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::VolumeOnboardingCreate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe IbmCloudPower::VolumeOnboardingCreate do
  let(:instance) { IbmCloudPower::VolumeOnboardingCreate.new }

  describe 'test an instance of VolumeOnboardingCreate' do
    it 'should create an instance of VolumeOnboardingCreate' do
      expect(instance).to be_instance_of(IbmCloudPower::VolumeOnboardingCreate)
    end
  end
  describe 'test attribute "volumes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
