=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 1.0.0
Contact: kylej@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-beta2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for IbmCloudPower::VolumesCloneAsyncRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VolumesCloneAsyncRequest' do
  before do
    # run before each test
    @instance = IbmCloudPower::VolumesCloneAsyncRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VolumesCloneAsyncRequest' do
    it 'should create an instance of VolumesCloneAsyncRequest' do
      expect(@instance).to be_instance_of(IbmCloudPower::VolumesCloneAsyncRequest)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "volume_i_ds"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
