language: ruby
dist: trusty
cache: bundler

notifications:
  email: true

matrix:
  fast_finish: true 

before_install:
  - git fetch --tags
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install node
  - nvm use node
  - gem install bundler:1.16.3

install:
  - bundle _1.16.3_ install

script:
- bundle exec rake

# To enable semantic-release, uncomment these sections.
# before_deploy:
#  - pip install --user bumpversion
#  - npm install -g semantic-release
#  - npm install -g @semantic-release/changelog
#  - npm install -g @semantic-release/exec
#  - npm install -g @semantic-release/git
#  - npm install -g @semantic-release/github
#  - npm install -g @semantic-release/commit-analyzer
# 
# deploy:
# - provider: script
#   script: npx semantic-release
#   skip_cleanup: true
#   on:
#     branch: main
#     rvm: 2.5.1
#
# - provider: rubygems
#   api_key: $RUBYGEMS_API_KEY
#   gem: ibm_cloud_resource_manager
#   on:
#     rvm: '2.5.1'
#     branch: main
#
