name: Update IBM Cloud SDK gems from OpenAPI Specs
on:
  schedule:
  - cron: 0 0 * * 0
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  openapi-generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - gem_name: ibm_cloud_databases
          spec_url: https://cloud.ibm.com/apidocs/cloud-databases-api/cloud-databases-api-v5.json
          spec_file: cloud-databases-api-cloud-databases-api-v5.json
        - gem_name: ibm_cloud_global_tagging
          spec_url: https://cloud.ibm.com/apidocs/tagging.json
          spec_file: tagging.json
        - gem_name: ibm_cloud_iam
          spec_url: https://cloud.ibm.com/apidocs/iam-identity-token-api.json
          spec_file: iam-identity-token-api.json
        - gem_name: ibm_cloud_power
          spec_url: https://cloud.ibm.com/apidocs/power-cloud.json
          spec_file: power-cloud.json
        - gem_name: ibm_cloud_resource_controller
          spec_url: https://cloud.ibm.com/apidocs/resource-controller/resource-controller.json
          spec_file: resource-controller-resource-controller.json
    steps:
    - uses: actions/checkout@v7
    - name: Set up system
      run: sudo apt install -y xq
    - name: Download OpenAPI Spec
      run: |
        curl --location ${{ matrix.spec_url }} --output "${{ matrix.spec_file }}"
    - name: OpenAPI Generate
      env:
        GEM_NAME: ${{ matrix.gem_name }}
        INPUT_SPEC: ${{ matrix.spec_file }}
      run: bin/openapi-generate
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        add-paths: |
          gems/${{ matrix.gem_name }}
        commit-message: Update ${{ matrix.gem_name }} gem
        branch: openapi_generate_${{ matrix.gem_name }}
        author: IBM Jeeves <ibm-jeeves@ibm.com>
        committer: IBM Jeeves <ibm-jeeves@ibm.com>
        delete-branch: true
        labels: enhancement
        assignees: agrare
        push-to-fork: ibm-jeeves/ibm-cloud-sdk-ruby
        title: Update ${{ matrix.gem_name }} gem from OpenAPI spec
        body: |
          Update the ${{ matrix.gem_name }} gem from the IBM Cloud OpenAPI specification.

          Spec URL: ${{ matrix.spec_url }}

          This PR was automatically generated by the openapi-generate workflow.
        token: "${{ secrets.GH_TOKEN }}"
