=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 1.0.0
Contact: kylej@us.ibm.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'date'
require 'time'

module IbmCloudPower
  class CloudConnectionSpeed
    N50 = 50.freeze
    N100 = 100.freeze
    N200 = 200.freeze
    N500 = 500.freeze
    N1000 = 1000.freeze
    N2000 = 2000.freeze
    N5000 = 5000.freeze
    N10000 = 10000.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CloudConnectionSpeed.constants.select { |c| CloudConnectionSpeed::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CloudConnectionSpeed" if constantValues.empty?
      value
    end
  end
end
