=begin
#Power Cloud API

#IBM Power Cloud API for Power Hardware / Infrastructure

The version of the OpenAPI document: 2.3.1
Contact: ismirlia@us.ibm.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module IbmCloudPower
  class CloudConnection
    attr_accessor :classic

    # cloud connection ID
    attr_accessor :cloud_connection_id

    # type of service the gateway is attached to
    attr_accessor :connection_mode

    # creation date
    attr_accessor :creation_date

    # enable global routing for this cloud connection (default=false)
    attr_accessor :global_routing

    # IBM IP address
    attr_accessor :ibm_ip_address

    # link status
    attr_accessor :link_status

    # metered
    attr_accessor :metered

    # name of the cloud connection
    attr_accessor :name

    # Network References
    attr_accessor :networks

    # port
    attr_accessor :port

    # speed of the cloud connection (speed in megabits per second)
    attr_accessor :speed

    # user IP address
    attr_accessor :user_ip_address

    attr_accessor :vpc

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'classic' => :'classic',
        :'cloud_connection_id' => :'cloudConnectionID',
        :'connection_mode' => :'connectionMode',
        :'creation_date' => :'creationDate',
        :'global_routing' => :'globalRouting',
        :'ibm_ip_address' => :'ibmIPAddress',
        :'link_status' => :'linkStatus',
        :'metered' => :'metered',
        :'name' => :'name',
        :'networks' => :'networks',
        :'port' => :'port',
        :'speed' => :'speed',
        :'user_ip_address' => :'userIPAddress',
        :'vpc' => :'vpc'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'classic' => :'CloudConnectionClassic',
        :'cloud_connection_id' => :'String',
        :'connection_mode' => :'String',
        :'creation_date' => :'Time',
        :'global_routing' => :'Boolean',
        :'ibm_ip_address' => :'String',
        :'link_status' => :'String',
        :'metered' => :'Boolean',
        :'name' => :'String',
        :'networks' => :'Array<NetworkReference>',
        :'port' => :'String',
        :'speed' => :'Integer',
        :'user_ip_address' => :'String',
        :'vpc' => :'CloudConnectionVpc'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `IbmCloudPower::CloudConnection` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `IbmCloudPower::CloudConnection`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'classic')
        self.classic = attributes[:'classic']
      end

      if attributes.key?(:'cloud_connection_id')
        self.cloud_connection_id = attributes[:'cloud_connection_id']
      else
        self.cloud_connection_id = nil
      end

      if attributes.key?(:'connection_mode')
        self.connection_mode = attributes[:'connection_mode']
      end

      if attributes.key?(:'creation_date')
        self.creation_date = attributes[:'creation_date']
      else
        self.creation_date = nil
      end

      if attributes.key?(:'global_routing')
        self.global_routing = attributes[:'global_routing']
      else
        self.global_routing = nil
      end

      if attributes.key?(:'ibm_ip_address')
        self.ibm_ip_address = attributes[:'ibm_ip_address']
      else
        self.ibm_ip_address = nil
      end

      if attributes.key?(:'link_status')
        self.link_status = attributes[:'link_status']
      else
        self.link_status = nil
      end

      if attributes.key?(:'metered')
        self.metered = attributes[:'metered']
      else
        self.metered = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'networks')
        if (value = attributes[:'networks']).is_a?(Array)
          self.networks = value
        end
      end

      if attributes.key?(:'port')
        self.port = attributes[:'port']
      else
        self.port = nil
      end

      if attributes.key?(:'speed')
        self.speed = attributes[:'speed']
      else
        self.speed = nil
      end

      if attributes.key?(:'user_ip_address')
        self.user_ip_address = attributes[:'user_ip_address']
      else
        self.user_ip_address = nil
      end

      if attributes.key?(:'vpc')
        self.vpc = attributes[:'vpc']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @cloud_connection_id.nil?
        invalid_properties.push('invalid value for "cloud_connection_id", cloud_connection_id cannot be nil.')
      end

      if @creation_date.nil?
        invalid_properties.push('invalid value for "creation_date", creation_date cannot be nil.')
      end

      if @global_routing.nil?
        invalid_properties.push('invalid value for "global_routing", global_routing cannot be nil.')
      end

      if @ibm_ip_address.nil?
        invalid_properties.push('invalid value for "ibm_ip_address", ibm_ip_address cannot be nil.')
      end

      if @link_status.nil?
        invalid_properties.push('invalid value for "link_status", link_status cannot be nil.')
      end

      if @metered.nil?
        invalid_properties.push('invalid value for "metered", metered cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @port.nil?
        invalid_properties.push('invalid value for "port", port cannot be nil.')
      end

      if @speed.nil?
        invalid_properties.push('invalid value for "speed", speed cannot be nil.')
      end

      if @user_ip_address.nil?
        invalid_properties.push('invalid value for "user_ip_address", user_ip_address cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @cloud_connection_id.nil?
      return false if @creation_date.nil?
      return false if @global_routing.nil?
      return false if @ibm_ip_address.nil?
      return false if @link_status.nil?
      return false if @metered.nil?
      return false if @name.nil?
      return false if @port.nil?
      return false if @speed.nil?
      return false if @user_ip_address.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] cloud_connection_id Value to be assigned
    def cloud_connection_id=(cloud_connection_id)
      if cloud_connection_id.nil?
        fail ArgumentError, 'cloud_connection_id cannot be nil'
      end

      @cloud_connection_id = cloud_connection_id
    end

    # Custom attribute writer method with validation
    # @param [Object] creation_date Value to be assigned
    def creation_date=(creation_date)
      if creation_date.nil?
        fail ArgumentError, 'creation_date cannot be nil'
      end

      @creation_date = creation_date
    end

    # Custom attribute writer method with validation
    # @param [Object] global_routing Value to be assigned
    def global_routing=(global_routing)
      if global_routing.nil?
        fail ArgumentError, 'global_routing cannot be nil'
      end

      @global_routing = global_routing
    end

    # Custom attribute writer method with validation
    # @param [Object] ibm_ip_address Value to be assigned
    def ibm_ip_address=(ibm_ip_address)
      if ibm_ip_address.nil?
        fail ArgumentError, 'ibm_ip_address cannot be nil'
      end

      @ibm_ip_address = ibm_ip_address
    end

    # Custom attribute writer method with validation
    # @param [Object] link_status Value to be assigned
    def link_status=(link_status)
      if link_status.nil?
        fail ArgumentError, 'link_status cannot be nil'
      end

      @link_status = link_status
    end

    # Custom attribute writer method with validation
    # @param [Object] metered Value to be assigned
    def metered=(metered)
      if metered.nil?
        fail ArgumentError, 'metered cannot be nil'
      end

      @metered = metered
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] port Value to be assigned
    def port=(port)
      if port.nil?
        fail ArgumentError, 'port cannot be nil'
      end

      @port = port
    end

    # Custom attribute writer method with validation
    # @param [Object] speed Value to be assigned
    def speed=(speed)
      if speed.nil?
        fail ArgumentError, 'speed cannot be nil'
      end

      @speed = speed
    end

    # Custom attribute writer method with validation
    # @param [Object] user_ip_address Value to be assigned
    def user_ip_address=(user_ip_address)
      if user_ip_address.nil?
        fail ArgumentError, 'user_ip_address cannot be nil'
      end

      @user_ip_address = user_ip_address
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          classic == o.classic &&
          cloud_connection_id == o.cloud_connection_id &&
          connection_mode == o.connection_mode &&
          creation_date == o.creation_date &&
          global_routing == o.global_routing &&
          ibm_ip_address == o.ibm_ip_address &&
          link_status == o.link_status &&
          metered == o.metered &&
          name == o.name &&
          networks == o.networks &&
          port == o.port &&
          speed == o.speed &&
          user_ip_address == o.user_ip_address &&
          vpc == o.vpc
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [classic, cloud_connection_id, connection_mode, creation_date, global_routing, ibm_ip_address, link_status, metered, name, networks, port, speed, user_ip_address, vpc].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = IbmCloudPower.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
